# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)

# Content configuration version
version: 2

# Personal info
name: Haiyue Liu
title: Student at University of Wisconsin-Madison
email: hliu746@wisc.edu / haiyueliu1122@gmail.com

phone: 7797752283

website: Heyweol.github.io



darkmode: false


github_username:  Heyweol

linkedin_username: Haiyue Liu

about_profile_image: images/IMG_ResumeUsed.JPG
about_content: | 
  Welcome to my page! My name is Haiyue Liu, and I major in Cartography & GIS and Computer Science at University of Wisconsin-Madison in my junior year.

content:

  - title: Experience
    layout: list
    content:
      - layout: right
        title: Byte Dance
        sub_title: Intern AI Developer
        caption: June-Aug.2023
        link: https://www.bytedance.com/en/
        
        description: | # this will include new lines to allow paragraphs
          •	Assisted to develop algorithms to build and refine the language model.

          •	Managed large computational resources necessary for training large models.

          •	Trained the model using state-of-the-art deep learning frameworks.

      - layout: right
        title: Spatial Computing and Data Mining Lab at University of Wisconsin-Madison                         
        sub_title: Research Assistant 
        caption: May.2023-present
        link: https://scdm.geography.wisc.edu
        
        description: | # this will include new lines to allow paragraphs
          •	Mapped and Completed GIS analysis Potential Impact of Florida SB264 (Agricultural Land, Critical Infrastructure and Military Installation Zone).

          •	Leveraged Python for Machine Learning in Research.

          •	Creation of an interactive online map presentation web page for the results of the study

      - layout: right
        title: Koop Lab at Northern Illinois University, Biology Department                         
        sub_title: Research Assistant 
        caption: Aug.—Dec.2022
        link: https://jenniferkoop.weebly.com
        
        description: | # this will include new lines to allow paragraphs
          •	Produced maps of habitats and migration routes of waterfowl creatures along the Mississippi River with ArcGIS Pro and MATLAB; gave software tutorials to other assistants and students in the lab.

          •	Watched over the faucet snails in the lab; monitored and reported their stats.

          •	Read and synopsized research on ecological geography to report during weekly meetings.

      - layout: top-right
        title: University of Chicago-Peking University Environmental Economics & Policy Lab                                                                                                   
        sub_title: Summer school
        caption: July-Aug.23
        description: | # this will include new lines to allow paragraphs
          Analysis of ESG Report Content in Traditional Industries
        
          •	Data Collection and Analysis: Harvested and scrutinized ESG reports from traditional companies in the textile, construction, and cement industries spanning the last 10 years to assess their adherence to social responsibility mandates.
        
          •	Python Scripting: Utilized Python for data cleansing and analytical operations, investigating the economic performance, investment strategies, and societal trust of targeted companies over a decade, positioning myself well to manage large data sets and conduct complex analyses, a critical skill set for a quantitative analyst.
        

          Analysis of Environmental and Geographic Issues in South Korea
        
          •	Geospatial Analysis: Conducted a detailed analysis of population distribution in various geographical contexts in South Korea, summarizing energy consumption patterns and identifying prevalent issues in the contemporary geographic landscape, a foundation for understanding complex systems and identifying trends.
        
          •	Sustainability Consulting: Formulated sustainable development solutions, leveraging policy support and governance to harmonize sustainable and non-sustainable resources, thereby enhancing geographic biodiversity and advocating for natural resource conservation, showcasing an ability to develop strategies based on analytical findings, a valuable asset for quantitative analysis roles.


  - title: Education
    layout: list
    content:
      - layout: top-right
        title: University of Wisconsin-Madison                                                                                                    
        sub_title: Undergraduate Studies in Cartography and Geographic Information Systems, Computer Science
        caption: Sept.23-present
      - layout: top-right
        title: Northern Illinois University                                                                                                   
        sub_title: Undergraduate Studies in Geography Information Systems
        caption: Sept.21-June.23

        # description: | 
  - title: My Skills & A Little More About Me :)
    layout: text
    content: |
      <Language:> C++, Python, Java, JavaScript, HTML5, CSS

      <GIS:> ArcGIS Pro, Arc GIS, QGIS, Google Earth

      <Data:> SQL, Mongo DB, MATLAB, SPSS, Tableau, R

      <Others:> Adobe software (Photoshop, Lightroom, Acrobat)

      I'm presently in my junior year pursuing dual majors in Cartography & GIS and Computer Science at the University of Wisconsin-Madison. 

      I'm keen on leveraging my background in GIS analysis and software development to work on projects that sit at the intersection of both fields. 

      My academic background arms me with the skills to analyze spatial data intricately and develop robust computer programs.

      I'm looking forward to finding an internship work in summer 2024. 
  

footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
